### ISSUE TITLE
Require the first recp to always be a groupId

### ISSUE THREAD

**Issue by Powersource** [ssbc/private-group-spec#20]
For most messages this'd mean that we'd disallow a feedId being the first entry in the `recps` array, i.e. every ID in recps being a feed id. In the init message which doesn't have an explicit `recps` array, this still applies in spirit since the recipient code currently looks like

```js
      const recipientKeys = [
        { key: groupKey.toBuffer(), scheme: keySchemes.private_group },
      ]

      ssb.db.create(
        {
          content,
          recps: recipientKeys,
          encryptionFormat: 'box2',
        },
```

I'm suggesting this as a modification to the Direct Messages spec https://github.com/ssbc/private-group-spec/tree/master/direct-messages to make this standard simpler. My hunch so far is that the DM spec introduces a lot of edge cases. We could make the spec more open in the future, but I don't see the harm in being more strict at least initially.

**Comment by Powersource** [comment]
@arj03 @mixmix @staltz

**Comment by staltz** [comment]
> Require the first recp to always be a groupId

I thought this was already enforced somewhere? In ssb-box2 maybe.

In any case, I'm favorable of this. But Mix is the person for all things private-group-spec.

**Comment by Powersource** [comment]
> I thought this was already enforced somewhere? In ssb-box2 maybe.

Idk but this spec doesn't disallow it to be a feedId

**Comment by mixmix** [comment]
The rule i have set up and follow is
- there may be a maximum of one groupId in the recps and
- if there is any group id it must be in the first slot


I don't understand what your problem/ issue is from what you've written here?

**Comment by Powersource** [comment]
@mixmix

**Comment by Powersource** [comment]
@mixmix boop

**Comment by mixmix** [comment]
what do you do with the first slot if you have no groupId then? e.g. in case of DM or PO Box?

**Comment by mixmix** [comment]
cc @Powersource

**Comment by Powersource** [comment]
@mixmix  All the cases we've talked about so far I think that are DMs are either adding a new member or sending a member a new key. In both of those cases we have a group id. PO boxes are also not a thing yet in v2.

**Comment by mixmix** [comment]
PO Box is the mechanism by which we will do "request to join group"

I don't personally think this is a worthwhile optimisation. It's very easy to go check the type with new ssb-uri formats?

**Comment by Powersource** [comment]
> when we use DMs standalone ever

I just don't see this happening I guess, and feels weird to leave implied support for it in the spec when tribes2 doesn't really support it. But I'm fine with not discussing this more.
